import React, { useContext } from "react";
import { ThemeContext } from "./context/ThemeContext"; // Adjust the import path
import { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import ThemeContextProvider from "./context/ThemeContext"; 
import CssBaseline from '@mui/material/CssBaseline';

export const metadata: Metadata = {
  title: "Nova",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <Providers>
            {children}
            <CssBaseline />
          </Providers>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
