name: Test Deploy to SSH Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes:  15

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (if you want this part)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true
          cache: 'yarn'

      

      # Deploy to SSH server
      - name: Deploy to SSH server
        uses: appleboy/ssh-action@master
        with:
          host: 194.163.167.131
          port: 22
          username: root
          password: bxnnHBAuNECS3a6m
         # key: ${{ secrets.SSH_PRIVATE_KEY }}  # Recommended for security, use secrets
         # fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: |
            # Go to the project folder
            cd ~/nova/novamis/Frontend-Nova

            # Stash local changes, if any, and pull the latest code from the main branch
            git stash
            git pull origin main

            # Load NVM and set up Node.js if not already available
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # Install Yarn globally if not already installed
            npm i -g yarn

            # Install project dependencies
            yarn install

            # Ensure the test environment script is executable and run it
            chmod +x scripts/create_test_env.sh
            ./scripts/create_test_env.sh

            # Build the project (Next.js)
            yarn run build

            # Start or restart the frontend app with PM2
            pm2 restart "nova-frontend" || pm2 start npm --name "nova-frontend" -- start -- -p 3030
