name: Test Deploy to SSH Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true
          cache: 'yarn'

      # Deploy to SSH server
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/nova/novamis/Frontend-Nova
            
            # Stash local changes and pull the latest code
            git stash
            git pull origin main
            
            # Load NVM and set up Node.js
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 20
            
            # Install Yarn globally if not already installed
            npm install -g yarn
            
            # Install project dependencies
            yarn install
            
            # Check if the test environment script exists
            if [ -f scripts/create_test_env.sh ]; then
                chmod +x scripts/create_test_env.sh
                ./scripts/create_test_env.sh
            else
                echo "Warning: scripts/create_test_env.sh not found."
            fi
            
            # Build the project (Next.js)
            yarn run build
            
            # Start or restart the frontend app with PM2
            pm2 restart "nova-frontend" || pm2 start npm --name "nova-frontend" -- start -- -p 3030
