name: Test Deploy to SSH Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true
          cache: 'yarn'

      # Deploy to SSH server
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: 194.163.167.131
          port: 22
          username: root
          password: bxnnHBAuNECS3a6m
          script: |
            cd ~/nova/novamis/Frontend-Nova
            
            # Stash local changes and pull the latest code
            git stash
            git pull origin main
            
            # Load NVM and set up Node.js
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            export PATH="$NVM_DIR/versions/node/$(nvm version)/bin:$PATH"
            
            npm install -g yarn
            
            yarn install --network-timeout 100000

            # Build the project (Next.js)
            yarn run build
            
            # Start or restart the frontend app with PM2
            pm2 restart "nova-frontend" || pm2 start npm --name "nova-frontend" -- start -- -p 3030
